bash
cat <<EOT > .github/workflows/weekly_sast.yml
name: Weekly SAST Scan

on:
schedule:
 - cron: '0 0 * * 0' # Elke zondag om middernacht

jobs:
sast_scan:
 name: Static Application Security Testing
 runs-on: ubuntu-latest

 steps:
   - name: Checkout code
     uses: actions/checkout@v3

   - name: Set up Python
     uses: actions/setup-python@v4
     with:
       python-version: '3.x'

   - name: Install Bandit
     run: |
       python -m pip install --upgrade pip
       pip install bandit

   - name: Run Bandit
     run: bandit -r .


